apiVersion: console.hypercloud.io/v1beta1
kind: ConsoleConfig
consoleInfo:
  listen: https://172.30.246.128:9000
  baseAddress: "https://172.30.246.128:9000"
  basePath: "/"
  certFile: "tls/tls.crt"
  keyFile: "tls/tls.key"
  redirectPort: 0
auth:
  keycloakClientId: ck-integration-hypercloud5
  keycloakRealm: tmax
  keycloakAuthURL: https://hyperauth.org/auth/
clusterInfo:
  k8sEndpoint: https://192.168.6.171:6443
  hypercloudEndpoint: ""
  multiHypercloudEndpoint: ""
  webhookEndpoint: ""
  alertmanagerEndpoint: ""
  grafanaEndpoint: "" 
  prometheusEndpoint: "http://172.23.4.201:30159/api"
  thanosEndpoint: ""
customization: 
  # branding: ""
  mcMode: false
  releaseMode: true
  # customProductName: ""
  # customLogoFile: ""
  publicDir: "./frontend/public/dist"
  
